# Generated by Django 4.2.1 on 2023-12-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temprature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
